name: Build and deploy application to Github Packages Maven repo

on:
  pull_request:
    types:
    - closed

jobs:
  bump-package-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Consider using commit hash or forking to avoid changes/security issues .. 
      - name: Bump version
        uses:  'steffenz/gh-action-bump-version@fix/branch-close-null-pointer'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'main'
