name: Build and deploy application to Github Packages Maven repo

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
