name: Build and deploy application to Github Packages Maven repo

on:
  release:
    types:
      - published

permissions:
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish
        run: npm publish
